# Generated by Django 3.0.7 on 2020-12-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.FileField(default='', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
