# Generated by Django 3.0.7 on 2020-12-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='post',
            field=models.CharField(max_length=200),
        ),
    ]
