# Generated by Django 3.0.7 on 2020-12-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201211_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='post',
            field=models.CharField(max_length=100),
        ),
    ]
